apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rhel-9-minimalpvc
spec:
  dataSourceRef:
    apiGroup: cdi.kubevirt.io
    kind: VolumeCloneSource
    name: rhel-9-minimalpvc
  accessModes:
  - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 30Gi
