apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
 name: rhel-9-minimalpvc
spec:
  instancetype:
    name: u1.medium
  preference:
    name: rhel.9
  runStrategy: Always
  template:
    spec:
      domain:
        devices: {}
      volumes:
        - persistentVolumeClaim:
            claimName: rhel-9-minimalpvc
          name: rootdisk
