apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: rhel9
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
spec:
  sourceRef:
    kind: DataSource
    name: rhel9
    namespace: openshift-virtualization-os-images
  storage: {}
