apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: exampleproject
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/dominikholler/gitopsexample.git
      revision: HEAD
      directories:
      - path: exampleproject/vms/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/dominikholler/gitopsexample.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: exampleproject
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
